/**
 * Master list of well-known fly patterns to discover and scrape.
 * Organized by category for targeted searching.
 */

interface SeedPattern {
  name: string;
  category: string;
}

export const SEED_PATTERNS: SeedPattern[] = [
  // ─── Dry Flies ──────────────────────────────────────────────────────────────
  { name: "Adams", category: "dry" },
  { name: "Parachute Adams", category: "dry" },
  { name: "Elk Hair Caddis", category: "dry" },
  { name: "Blue Wing Olive", category: "dry" },
  { name: "Pale Morning Dun", category: "dry" },
  { name: "Royal Wulff", category: "dry" },
  { name: "Griffith's Gnat", category: "dry" },
  { name: "Stimulator", category: "dry" },
  { name: "Humpy", category: "dry" },
  { name: "Hendrickson", category: "dry" },
  { name: "Comparadun", category: "dry" },
  { name: "Sparkle Dun", category: "dry" },
  { name: "X-Caddis", category: "dry" },
  { name: "Light Cahill", category: "dry" },
  { name: "March Brown", category: "dry" },
  { name: "Quill Gordon", category: "dry" },
  { name: "Trico Spinner", category: "dry" },
  { name: "Goddard Caddis", category: "dry" },
  { name: "Dave's Hopper", category: "dry" },
  { name: "Joe's Hopper", category: "dry" },
  { name: "Foam Beetle", category: "dry" },
  { name: "Hi-Vis Ant", category: "dry" },
  { name: "Chernobyl Ant", category: "dry" },
  { name: "Improved Sofa Pillow", category: "dry" },
  { name: "Yellow Sally", category: "dry" },
  { name: "Ausable Wulff", category: "dry" },
  { name: "Irresistible", category: "dry" },
  { name: "CDC Emerger", category: "dry" },
  { name: "Renegade", category: "dry" },
  { name: "Gray Fox", category: "dry" },
  { name: "Blue Dun", category: "dry" },
  { name: "Sulphur Dun", category: "dry" },
  { name: "Thorax Dun", category: "dry" },
  { name: "Olive Sparkle Dun", category: "dry" },
  { name: "Cinnamon Caddis", category: "dry" },
  { name: "Green Drake", category: "dry" },
  { name: "Brown Drake", category: "dry" },
  { name: "Rusty Spinner", category: "dry" },
  { name: "Henryville Special", category: "dry" },
  { name: "Fluttering Caddis", category: "dry" },
  { name: "Missing Link Caddis", category: "dry" },
  { name: "Letort Hopper", category: "dry" },
  { name: "Turck's Tarantula", category: "dry" },
  { name: "Madam X", category: "dry" },
  { name: "Purple Haze", category: "dry" },

  // ─── Nymphs ─────────────────────────────────────────────────────────────────
  { name: "Pheasant Tail Nymph", category: "nymph" },
  { name: "Gold Ribbed Hare's Ear", category: "nymph" },
  { name: "Prince Nymph", category: "nymph" },
  { name: "Copper John", category: "nymph" },
  { name: "Zebra Midge", category: "nymph" },
  { name: "RS2", category: "nymph" },
  { name: "WD-40", category: "nymph" },
  { name: "Brassie", category: "nymph" },
  { name: "San Juan Worm", category: "nymph" },
  { name: "Pat's Rubber Legs", category: "nymph" },
  { name: "Perdigon Nymph", category: "nymph" },
  { name: "Frenchie", category: "nymph" },
  { name: "Walt's Worm", category: "nymph" },
  { name: "Lightning Bug", category: "nymph" },
  { name: "Squirmy Wormy", category: "nymph" },
  { name: "Mop Fly", category: "nymph" },
  { name: "Soft Hackle Pheasant Tail", category: "nymph" },
  { name: "Zug Bug", category: "nymph" },
  { name: "Bird's Nest", category: "nymph" },
  { name: "Bead Head Flashback Pheasant Tail", category: "nymph" },
  { name: "Tellico Nymph", category: "nymph" },
  { name: "Stonefly Nymph", category: "nymph" },
  { name: "Golden Stonefly Nymph", category: "nymph" },
  { name: "Twenty Incher", category: "nymph" },
  { name: "Serendipity", category: "nymph" },
  { name: "Mercury Pheasant Tail", category: "nymph" },
  { name: "Mercury Black Beauty", category: "nymph" },
  { name: "Barr's Emerger", category: "nymph" },
  { name: "Two Bit Hooker", category: "nymph" },
  { name: "Juju Baetis", category: "nymph" },
  { name: "Top Secret Midge", category: "nymph" },
  { name: "Flashback Hare's Ear", category: "nymph" },
  { name: "Black Beauty", category: "nymph" },
  { name: "Disco Midge", category: "nymph" },
  { name: "Dorsey's Mercury Midge", category: "nymph" },
  { name: "Ray Charles", category: "nymph" },
  { name: "Micro Mayfly", category: "nymph" },
  { name: "Loebergs Drifter", category: "nymph" },
  { name: "Psycho Prince", category: "nymph" },
  { name: "Thread Midge", category: "nymph" },
  { name: "Caddis Larva", category: "nymph" },
  { name: "Green Weenie", category: "nymph" },
  { name: "Egg Pattern", category: "nymph" },

  // ─── Streamers ──────────────────────────────────────────────────────────────
  { name: "Woolly Bugger", category: "streamer" },
  { name: "Clouser Minnow", category: "streamer" },
  { name: "Muddler Minnow", category: "streamer" },
  { name: "Zonker", category: "streamer" },
  { name: "Slump Buster", category: "streamer" },
  { name: "Sex Dungeon", category: "streamer" },
  { name: "Circus Peanut", category: "streamer" },
  { name: "Zoo Cougar", category: "streamer" },
  { name: "Meat Whistle", category: "streamer" },
  { name: "Game Changer", category: "streamer" },
  { name: "Barely Legal", category: "streamer" },
  { name: "Sculpzilla", category: "streamer" },
  { name: "Craft Fur Sculpin", category: "streamer" },
  { name: "Mini Dungeon", category: "streamer" },
  { name: "Thin Mint", category: "streamer" },
  { name: "Conehead Woolly Bugger", category: "streamer" },
  { name: "Mickey Finn", category: "streamer" },
  { name: "Black Ghost", category: "streamer" },
  { name: "Gray Ghost", category: "streamer" },
  { name: "Matuka", category: "streamer" },
  { name: "Bow River Bugger", category: "streamer" },
  { name: "Sparkle Minnow", category: "streamer" },
  { name: "Articulated Shank Streamer", category: "streamer" },
  { name: "Double Bunny", category: "streamer" },
  { name: "Heifer Groomer", category: "streamer" },
  { name: "Bunny Leech", category: "streamer" },
  { name: "Pine Squirrel Leech", category: "streamer" },
  { name: "Egg Sucking Leech", category: "streamer" },
  { name: "Zuddler", category: "streamer" },
  { name: "White Zonker", category: "streamer" },

  // ─── Emergers ───────────────────────────────────────────────────────────────
  { name: "Klinkhammer", category: "emerger" },
  { name: "Barr Emerger", category: "emerger" },
  { name: "Snowshoe Emerger", category: "emerger" },
  { name: "Film Critic", category: "emerger" },
  { name: "Quigley Cripple", category: "emerger" },
  { name: "Cannon's Snowshoe Dun", category: "emerger" },
  { name: "Stuck in the Shuck", category: "emerger" },
  { name: "CDC Transitional Dun", category: "emerger" },
  { name: "Harrop's CDC Biot Emerger", category: "emerger" },
  { name: "Sparkle Pupa", category: "emerger" },
  { name: "Deep Sparkle Pupa", category: "emerger" },
  { name: "Soft Hackle Emerger", category: "emerger" },
  { name: "Partridge and Orange", category: "emerger" },
  { name: "Partridge and Green", category: "emerger" },
  { name: "Starling and Herl", category: "emerger" },
  { name: "Flymph", category: "emerger" },
  { name: "CDC Loopwing Emerger", category: "emerger" },
  { name: "Iris Caddis", category: "emerger" },
  { name: "LaFontaine Caddis Emerger", category: "emerger" },
  { name: "Swing Nymph", category: "emerger" },

  // ─── Saltwater ──────────────────────────────────────────────────────────────
  { name: "Lefty's Deceiver", category: "saltwater" },
  { name: "Crazy Charlie", category: "saltwater" },
  { name: "Gotcha", category: "saltwater" },
  { name: "Bonefish Bitters", category: "saltwater" },
  { name: "EP Baitfish", category: "saltwater" },
  { name: "Surf Candy", category: "saltwater" },
  { name: "Puglisi Baitfish", category: "saltwater" },
  { name: "Seaducer", category: "saltwater" },
  { name: "Tarpon Toad", category: "saltwater" },
  { name: "Cockroach", category: "saltwater" },
  { name: "Permit Crab", category: "saltwater" },
  { name: "Merkin Crab", category: "saltwater" },
  { name: "Borski's Slider", category: "saltwater" },
  { name: "Gurgler", category: "saltwater" },
  { name: "Clouser Crayfish", category: "saltwater" },
  { name: "Bend Back", category: "saltwater" },
  { name: "Half and Half", category: "saltwater" },
  { name: "Popovic's Banger", category: "saltwater" },
  { name: "Enrico's Spawning Shrimp", category: "saltwater" },
  { name: "Peterson's Spawning Shrimp", category: "saltwater" },
];

export function getPatternsByCategory(category: string): SeedPattern[] {
  return SEED_PATTERNS.filter((p) => p.category === category);
}

export function getPatternNames(): string[] {
  return SEED_PATTERNS.map((p) => p.name);
}
